---
- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart firewall
  ufw: state=reloaded

- name: restart monit
  monit:
    name: all
    state: reloaded

- name: restart postfix
  service: name=postfix state=restarted

- name: restart postgresql
  service: name=postgresql state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
  
- name: restart ssh
  service: name=ssh state=restarted

- name: restart sysstat
  service: name=sysstat state=restarted
