---
# These tasks ensure that core dumps are not created on the server.

# Note this will not take affect until users logout and back in.
- name: Configure /etc/security/limits.conf
  template: src=etc/security/limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0644
