---
# Run the apt task first to ensure packages are up to date before running the other tasks.
- include: apt.yml

- include: coredump.yml
- include: fail2ban.yml
- include: firewall.yml
- include: monit.yml
- include: packages.yml
- include: postgresql.yml
- include: postfix.yml
- include: ssh-server.yml
- include: sysstat.yml
- include: timezone.yml
- include: unattended-upgrades.yml

- include: crypt.yml
