---
###################################################################################################
# These tasks ensure that postgres is installed and configured.
#
# Postgres is our database of choice and will be used to run the Vault. The database data files
# will be stored on the encrypted filesystem. As such, this package must be run after crypt.
###################################################################################################

- name: Ensure postgres package is present
  apt:
    name: postgresql
    state: present

- name: Configure /etc/postgresql/9.5/main/postgresql.conf
  template:
    src: etc/postgresql/9.5/main/postgresql.conf.j2
    dest: /etc/postgresql/9.5/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgresql

- name: Configure /etc/postgresql/9.5/main/pg_hba.conf
  template:
    src: etc/postgresql/9.5/main/pg_hba.conf.j2
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify: restart postgresql

- name: Check to see if postgres data exists in encrypted space
  stat: path="{{ crypt_dir }}/var/lib/postgresql"
  register: postgresqlStat

- name: Ensure /var/lib is created in encrypted space
  file:
    path: "{{ crypt_dir }}/var/lib"
    state: directory

- name: Copy postgres data to encrypted space
  command: cp -r -p /var/lib/postgresql "{{ crypt_dir }}/var/lib/postgresql"
  when: postgresqlStat.stat.exists == False
  notify: restart postgresql

- name: Ensure postgres is started and NOT started on boot
  service:
    name: postgresql
    state: started
    enabled: no
  tags: startup
