---
# These tasks ensure the ssh server is installed and configured to:
# - Disable root login
# - Disable RSA authentication
# - Enable public key authentication
# - Disable empty passwords
# - Disable challenge response authentication
# - Disable kerberos
# - Disable X11 forwarding
# - Display banner (motd)

- name: Ensure the openssh-server package is present
  apt: name=openssh-server state=present

- name: Configure /etc/ssh/sshd_config
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify: restart ssh

- name: Configure /etc/issue.net (motd)
  template: src=etc/issue.net.j2 dest=/etc/issue.net owner=root group=root mode=0644
  notify: restart ssh
