---
# These tasks ensure that the timezone is set.

- fail: msg="Variable timezone is required"
  when: timezone is undefined

# Note that we restart the rsyslog because the time entries put into auth.log will be shifted
# which prevents fail2ban from working.
# https://stackoverflow.com/questions/20720129/fail2ban-not-banning-ssh-bruteforce-but-regex-works
- name: Set timezone
  timezone: name={{ timezone }}
  notify: restart rsyslog
