---
####################################################################################################
# These tasks create the system administrator accounts on the endpoint.
#
# Each system administrator will be granted their own account. Active system administrators will
# be in the sudo group. Inactive system administrators will be in the nossh group.
####################################################################################################

- name: Create nossh group
  group:
    name: nossh
    state: present

- name: Create system administrator accounts
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    state: present
    append: no
  with_items: "{{ users }}"

- name: Create system administrator authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
    manage_dir: yes
  with_items: "{{ users }}"

- name: Create the hdc user
  user:
    name: hdc
    comment: "Generic HDC user"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    state: present

- name: Fetch the generated key
  fetch:
    src: /home/hdc/.ssh/id_rsa.pub
    dest: "/tmp/ansible/public_keys/{{ hostname }}.pub"
    flat: yes
    fail_on_missing: yes

- name: Merge into LOCAL /home/endpoint/.ssh/authorized_keys
  local_action: lineinfile path=/home/endpoint/.ssh/authorized_keys regexp='{{ hostname }}' line="{{ lookup('file', '/tmp/ansible/public_keys/{{ hostname }}.pub') }}"
